name: Python CI

on:
  schedule:
    - cron: "*/30 * * * *"  # Запуск каждые 30 минут
  workflow_dispatch:  # Возможность запуска вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.9'  # Укажите нужную версию Python

    - name: Make start.sh executable
      run: chmod +x start.sh

    - name: Run start.sh
      run: ./start.sh
